image: docker:latest
cache:
  paths:
    - node_modules/

deploy_staging:
  stage: deploy
  environment:
    name: staging
  only:
    - tags
  script:
    - curl -o- -L https://yarnpkg.com/install.sh | bash
    - yarn global add typescript
    - (cd server; yarn; yarn build)
    - (cd server; docker build -t eu.gcr.io/qpa-staging-237606/qpa:$CI_COMMIT_TAG .)
    - docker push eu.gcr.io/qpa-staging-237606/qpa:$CI_COMMIT_TAG
build:
#  image: gcr.io/kaniko-project/executor:debug
  image: docker:latest
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - cat /kaniko/.docker/config.json
#    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --no-push
