stages:
  - build

build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    — echo "$GCE_SERVICE_ACCOUNT_KEY" > gce_key.json
    - docker login -u _json_key --password-stdin https://eu.gcr.io < gce_key.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --no-push

