apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-api
  annotations:
    # use the shared ingress-nginx
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: alpha.quepasaalpujarra.com
      http:
        paths:
          - path: /graphql
            backend:
              serviceName: api
              servicePort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    app: api
    tier: frontend
spec:
  ports:
    - port: 4000
      targetPort: 4000
  selector:
    app: api
    tier: frontend
---
apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: api
spec:
  selector:
    matchLabels:
      app: api
      tier: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: api
        tier: frontend
    spec:
      containers:
        - name: master
          image: eu.gcr.io/qpa-staging-237606/qpa:0.0.13
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 4000
          env:
            - name: DOMAIN
              value: "alpha.quapasaalpujarra.com"
            - name: DB_USER
              value: "qpa"
            - name: POSTGRES_DB
              value: "qpa"
            - name: DB_PASSWORD
              value: "1zrBGfidoPzf"
            - name: POSTGRES_HOST
              value: "10.79.112.3"
            - name: MAILGUN_KEY
              value: "key-59ad615180cb44e4ff5fd41236a9694a"
            - name: EMAIL_DOMAIN
              value: "staging.quepasaalpujarra.com"


